---
- hosts: all
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  roles:
  - role: znz.docker
  tasks:
  - name: "Add users to docker group"
    user:
      name: "{{ item }}"
      groups: docker
      append: yes
    with_items: "{{ docker_users }}"
  - name: "Allow forward tcp ports from docker"
    ufw:
      #delete: yes
      from_ip: "{{ allow_forward_docker }}"
      proto: tcp
      route: yes
      rule: allow
      to_port: "{{ item }}"
    with_items: "{{ allow_forward_tcp_ports_from_docker }}"
  - name: "Allow forward udp ports from docker"
    ufw:
      #delete: yes
      from_ip: "{{ allow_forward_docker }}"
      proto: udp
      route: yes
      rule: allow
      to_port: "{{ item }}"
    with_items: "{{ allow_forward_udp_ports_from_docker }}"
  - name: "Allow forward tcp/udp ports from docker"
    ufw:
      #delete: yes
      from_ip: "{{ allow_forward_docker }}"
      route: yes
      rule: allow
      to_port: "{{ item }}"
    with_items: "{{ allow_forward_both_ports_from_docker }}"
  - name: "Allow forward tcp ports to docker"
    ufw:
      #delete: yes
      direction: out
      from_ip: "{{ allow_forward_docker }}"
      proto: tcp
      rule: allow
      to_ip: "{{ allow_forward_docker }}"
      to_port: "{{ item }}"
    with_items: "{{ allow_forward_tcp_ports_to_docker }}"
