---
- hosts: all
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  roles:
  - role: znz.dokku
    dokku_vhost_enable: "true"
    dokku_web_config: "false"
    dokku_hostname: "{{ stage_dokku_hostname }}"
    dokku_skip_key_file: "{{ stage_dokku_skip_key_file }}"
    dokku_key_file: "{{ stage_dokku_key_file }}"
    dokku_plugin: "{{ stage_dokku_plugin }}"
  - role: znz.sshd
    sshd_allow_users:
    - 'dokku'
