---
- hosts: all
  become: yes
  vars_files:
  - vars/{{ stage }}.yml
  roles:
  - role: znz.dokku
    dokku_vhost_enable: "true"
    dokku_web_config: "false"
    dokku_hostname: "{{ stage_dokku_hostname }}"
    dokku_skip_key_file: "{{ stage_dokku_skip_key_file }}"
    dokku_key_file: "{{ stage_dokku_key_file }}"
    dokku_plugin: "{{ stage_dokku_plugin }}"
  - role: znz.sshd
    sshd_allow_users:
    - 'dokku'
  tasks:
  - name: 'ufw allow out on docker0 proto tcp'
    # allow nginx to app
    ufw:
      direction: out
      interface: docker0
      proto: tcp
      rule: allow
  - name: "Add nadoka to docker group for WatchBot"
    user:
      name: nadoka
      groups: docker
      append: yes
