---
- src: znzj.ja_jp
#- src: znz.ufw
- src: https://github.com/znz/ansible-role-ufw
  version: master
  name: znz.ufw
- src: znz.journald
- src: https://github.com/znz/ansible-role-sshd
  version: master
  name: znz.sshd
- src: znz.unattended-upgrades
- src: https://github.com/znz/ansible-role-nadoka
  version: master
  name: znz.nadoka
- src: https://github.com/znz/ansible-role-openvpn-server
  version: master
  name: znz.openvpn-server
