---
- hosts: all
  become: yes
  gather_facts: no
  vars_files:
  - vars/{{ stage }}.yml
  tasks:
  - name: "Install zabbix-agent"
    apt: name=zabbix-agent

  - name: '/etc/zabbix/zabbix_agentd.conf.d/crl_next_update.conf'
    copy:
      content: |
        UserParameter=crl.next_update.openvpn-server,ruby -r openssl -e 'p File.open(ARGV.shift){|f|OpenSSL::X509::CRL.new(f)}.next_update-Time.now' /etc/openvpn/server/crl.pem
        UserParameter=crl.openvpn-server,ruby -r openssl -e 'p File.open(ARGV.shift){|f|OpenSSL::X509::CRL.new(f)}.next_update-Time.now' /etc/openvpn/server/crl.pem
      dest: '/etc/zabbix/zabbix_agentd.conf.d/crl_next_update.conf'
      owner: 'root'
      group: 'zabbix'
      mode: 0644

  - name: '/etc/zabbix/zabbix_agentd.psk'
    copy:
      content: "{{ zabbix_agentd_psk }}"
      dest: '/etc/zabbix/zabbix_agentd.psk'
      owner: 'root'
      group: 'zabbix'
      mode: 0640

  - name: '/etc/zabbix/zabbix_agentd.conf.d/psk.conf'
    copy:
      content: |
        TLSConnect=psk
        TLSAccept=psk
        TLSPSKIdentity=ns7
        TLSPSKFile=/etc/zabbix/zabbix_agentd.psk
      dest: '/etc/zabbix/zabbix_agentd.conf.d/psk.conf'
      owner: 'root'
      group: 'zabbix'
      mode: 0644

  - name: '/etc/zabbix/zabbix_agentd.conf.d/server.conf'
    copy:
      content: |
        Server=127.0.0.1,{{ zabbix_agentd_servers | join(',') }}
      dest: '/etc/zabbix/zabbix_agentd.conf.d/server.conf'
      owner: 'root'
      group: 'zabbix'
      mode: 0644

  - name: 'ufw allow to zabbix_agentd'
    ufw:
      proto: tcp
      from_ip: "{{ item }}"
      rule: allow
      to_port: 10050
    with_items: "{{ zabbix_agentd_servers }}"

  - name: '/opt/nadoka/stat-fprog.sh'
    copy:
      content: |
        #!/bin/sh
        exec stat -c %s /tmp/systemd-private-*-nadoka@fprog.service-*/tmp/*/fprog-CS-servers/$(date +%y%m%d).log
      dest: '/opt/nadoka/stat-fprog.sh'
      owner: 'root'
      group: 'root'
      mode: 0755

  - name: '/opt/nadoka/stat-atig.sh'
    copy:
      content: |
        #!/bin/sh
        exec stat -c %s /home/nadoka/log/atig-$1/CS-twitter/$(date +%y/%m%d).log
      dest: '/opt/nadoka/stat-atig.sh'
      owner: 'root'
      group: 'root'
      mode: 0755

  - name: '/etc/sudoers.d/zabbix'
    copy:
      content: |
        zabbix ALL=(ALL) NOPASSWD:/opt/nadoka/stat-fprog.sh
        zabbix ALL=(ALL) NOPASSWD:/opt/nadoka/stat-atig.sh
      dest: '/etc/sudoers.d/zabbix'
      owner: 'root'
      group: 'root'
      mode: 0440
      validate: 'visudo -cf %s'

  - name: '/etc/zabbix/zabbix_agentd.conf.d/nadoka.conf'
    copy:
      content: |
        UserParameter=nadoka.stat.fprog,sudo /opt/nadoka/stat-fprog.sh
        UserParameter=nadoka.stat.atig[*],sudo /opt/nadoka/stat-atig.sh $1
      dest: '/etc/zabbix/zabbix_agentd.conf.d/nadoka.conf'
      owner: 'root'
      group: 'zabbix'
      mode: 0644

  - name: 'restart zabbix-agent'
    systemd:
      name: 'zabbix-agent.service'
      state: restarted
